version: 7.1.1
skip_non_tags: true
image: Visual Studio 2017
build_script:
- ps: .\Build\Build-Release.ps1 $env:APPVEYOR_BUILD_VERSION '' 1
artifacts:
- path: build\Release\*.nupkg
  name: Nuget Package
